### ISSUE TITLE
Schedule next release

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#203]
@M-Nicholls would like me to push all of the skinned hubs (APA, AMRIN, ASBP, Living Aeoteroa/Tepapa, OZCAM, OBIS, and MDBA) over to AWS (aws-hubs.ala.org.au) with the latest versions and fixes to remove that from my time schedule. To do that I need to have a release of this plugin and its dependencies (ala-charts-plugin and images-client-plugin are the direct dependencies that need releases before biocache-hubs). Since it has had changes during the October sprints I want to confirm that everything is ready for release or get a release date this week hopefully before I start working on the IEK sprint next week.

This would regain some servers in IM&T and NCI that are currently hosting some of those hubs.

AVH was deployed since I was last working on the hubs on another dedicated server at AWS (not aws-hubs.ala.org.au), so its timeline can be separate, but it will need a new deployment given the updates from this sprint cycle.

CC @adam-collins @patkyn @nickdos

**Comment by ansell** [comment]
I am going to start the release processes today, starting with the dependent plugins and hopefully getting all of the thin hubs released by the end of the day.

**Comment by ansell** [comment]
Testing setback, didn't notice that 1.2 was released already this week, but it had SNAPSHOT dependencies so it is inherently broken for testing purposes. Starting all testing again with 1.3-SNAPSHOT

**Comment by nickdos** [comment]
I'd suggest going with biocache-hubs version 1.1.4 for now... as it _was_ the most recent non-snapshot version in nexus.ala.org.au (until this week I think) and more recent than the current prod biocache (1.1.2). I think it has one snapshot dependency (it shouldn't I know) but I'd just go with it for now.

**Comment by nickdos** [comment]
I've seen that you are adding `ala-bootstrap2` plugin to the hubs... I don't think they should be using this plugin - they should be using the `ala-auth` one. I think we need a light-weight alternative to the `ala-bootstrap2` plugin to provide the resources file, JS & CSS files only. The issue is the `ala-bootstrap2` plugin has a version of the bootstrap CSS that has been customised for ALA (e.g. ALA orange for buttons, etc) plus it has a whole bunch of `taglibs` that are not needed (I think). Previously this was not needed as `biocache-hubs` contained non-customised bootstrap files but these were removed as a last resort due to a conflict with the images-client-plugin changes - from https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/604f0679c88004532b251789ef77edf106ebd836.

**Comment by ansell** [comment]
I am not familiar with why the bootstrap plugin fixes the errors, but you suggested it to me originally during the maintenance sprint. The issue tracking that was #193

Just managing the version for ala-auth didn't work for the hubs that previously used ala-web-theme, but could not use it anymore after biocache-hubs:1.0/1.1, and after biocache-hubs:1.0/1.1 ala-auth is pulled in for all thin hubs as a dependency.
