### ISSUE TITLE
Batch taxon name search

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#245]
On the search page, the "batch taxon search" tab...

It currently uses the "raw_name" field but some users want it to work the same way the "taxon name" (advanced tab) and simple search do, by performing a lookup on each name and converting to LSID search field.

Suggestion is to add options as follows:

- [x] ~Add radio button for match provided/raw name - `raw_name`~
- [x] ~Add radio button for accepted name - `taxon_name`~
- [x] ~Add radio button for match accepted name and synonyms - `taxa param`~
- [x] Add a toggle widget to choose whether matched name or provided name is used to search against. Default to matched name
- [x] add better help text explaining search is against provided name
- [x] ~~add option to be able to search against **both** provided and matched names~~

**Comment by charvolant** [comment]
Related to recent support query searching for a number of snake genera.

raw_name search also doesn't find records that are provided in eg. genus:Neelaps, specificEpithet:bimaculatus form, since there is no scientificName supplied.

**Comment by nickdos** [comment]
Code review requested on PR #521

**Comment by Rita-C** [comment]
Code looks good, move to QA.

**Comment by Rita-C** [comment]
**Default Profile ALA general**
- Search for Phyllanthus hirtellus should find ~10k reccords
      - matched name ->9,102 records
      - Supplied name ->8,715 records 
- Search for Phyllanthus thymoides should return the results for Phyllanthus hirtellus (synonym)
      - matched name ->9,102 records, same as Phyllanthus hirtellus (synonym)
      - Supplied name -> 10 records
- Search for Phyllanthus hirtellus F.Muell. ex Müll.Arg. in both raw and non-raw form. Raw form should return about 70 records, non-raw the lot
      - Supplied name -> 73 records 
      - matched name -> 
```
Application error
Failed to get json from web service (https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=qid%3A1642727109168&qualityProfile=ALA&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name%2Cfamily%2Cspecies_group%2Ccommon_name%2Cmonth%2Coccurrence_decade_i%2Cstate%2Cbasis_of_record%2Cmultimedia%2Coccurrence_status%2CcontentTypes%2Cassertion_user_id%2Cinstitution_uid%2Cdata_resource_uid&flimit=10). class org.grails.web.converters.exceptions.ConverterException Error parsing JSON, org.grails.web.converters.exceptions.ConverterException: Error parsing JSON; nested exception is org.grails.web.converters.exceptions.ConverterException: Error parsing JSON
```
  
- Search for Eucalyptus regnans and Eucalyptus regnins the latter should fail because it goes to a higher match
      - Eucalyptus regnans matched name -> 5,679 records
      - Eucalyptus regnans Supplied name -> 5,462 records
      - Eucalyptus regnins matched name -> 783,844 records 
      - Eucalyptus regnins Supplied name -> No records found for (Scientific name (unprocessed):"Eucalyptus regnins")
- Search for Wollemia nobilis and Wollemia nobilia the latter should fail because it is a misspelling (although matches W. nobilis so this may not be right)
      - Wollemia nobilia taxa (matched name) -> 59 records 
      - Wollemia nobilia -> No records found for (Scientific name (unprocessed):"Wollemia nobilia")
- Search for Eolophus roseicapilla and Eolophus roseicapillus these should give the same results (about 800k) when searching for matched names and half and half searching for raw name. Eolophus roseicapillus should be treated the same as E. roseicapilla in my opinion but that doesn’t seem to happen with the straight taxa search.
      - both returned 715,011 records when searching for matched names
      - (raw) Eolophus roseicapilla 411,186 records, Eolophus roseicapillus 266,378 records

**Comment by Rita-C** [comment]
defect reported as https://github.com/AtlasOfLivingAustralia/biocache-service/issues/734

**Comment by nickdos** [comment]
Thanks @Rita-C - I think that error for `Phyllanthus hirtellus F.Muell. ex Müll.Arg.` is unrelated to this change, as it appears to be a result of an unescaped `ü` char and its own bug.
