### ISSUE TITLE
Transfer of the various messages.properties files takes 2 to 3 seconds of walltime

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#264]
_From @ansell on February 16, 2017 22:33_

Search result page loads have a component of time totalling about 2 to 3 seconds where there are sporadic requests for a range of messages.properties/messages.en.properties/messages_en_US.properties files. If this process were streamlined it would increase the usability of the website.

_Copied from original issue: AtlasOfLivingAustralia/ala-hub#16_

**Comment by ansell** [comment]
![screen shot 2018-06-25 at 10 53 03 am](https://user-images.githubusercontent.com/82365/41825788-636f6df0-7867-11e8-8c41-332b7881edfc.png)

See this screenshot of the timings (possibly not all of the time around messages.properties are related to them)

**Comment by nickdos** [comment]
FYI, commit f84b317 added a 'cache' option that fixes the cache-busting issue. I also fixed the double loading of messages.properties on search pages and added the async option to stop modern browsers from complaining and to speed page loading.

**Comment by ansell** [comment]
The ``messages.properties`` files are not cache-busting anymore, based on testing this on ``biocache-test.ala.org.au``, but they aren't marked as cacheable by browsers. The other js resources are successfully using ``If-Modified-Since`` and ``Last-Modified`` headers for browser level caching. 

The duplicate queries have been fixed and the total page is down from 2.4MB (749KB gzipped) to 2.04MB (620KB gzipped) so overall definitely an improvement

There was a reference to ``cache: false`` in the commit above, was that meant to be ``cache: true``?

https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/f84b317129eb6be1bbae4a3e4eb84f8c38973912#diff-86d6a358349ac5abf2c98b5331271472R65

The main difference since the last timing analysis, is the dependency on ``s3.amazonaws.com`` for the freshdesk widget. This website seems to have a close to 0ms TTL on their DNS, which in effect seems to require a DNS query for an average of 2 out of the 3 resources, although it seems like they are asynchronous, so they aren't interfering with the total timeframe as much as it looks:
![screen shot 2018-11-07 at 3 55 48 pm](https://user-images.githubusercontent.com/82365/48111518-01f3bf00-e2a6-11e8-9a66-a64fd336acf8.png)

![screen shot 2018-11-07 at 3 54 42 pm](https://user-images.githubusercontent.com/82365/48111543-1a63d980-e2a6-11e8-87cd-1f5d36a70363.png)

**Comment by nickdos** [comment]
@ansell not sure where the reference to `false` was but it should be `cache:  true`.

**Comment by ansell** [comment]
The first messages.properties request is now interleaved, so this issue can be closed. The freshdesk widget is the biggest time factor now, other than optimising the initial page load which is currently at 2.6 seconds for the default search.

![screen shot 2018-11-08 at 9 25 56 am](https://user-images.githubusercontent.com/82365/48165083-93137600-e338-11e8-9ed2-9a5068a55499.png)

Should I open a new issue specific to ala-hub for the freshdesk widget optimisation in the future, given it isn't relevant to biocache-hubs?

**Comment by ansell** [comment]
Closing this as fixed based on testing. Opened an issue for freshdesk specifically at https://github.com/AtlasOfLivingAustralia/commonui-bs3/issues/2

**Comment by sylmorin-gbif** [comment]
Hi,

Caching of message.properties is not (no more?) active.
My browser spend around 5 seconds to download them on each page I see on ALA Portal.

I activated the caching on my portal (openobs.mnhn.fr) and I don't have this issue.
https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/develop/grails-app/assets/vendor/jquery.i18n.properties.js#L65

Regards,
Sylvain

![image](https://user-images.githubusercontent.com/56630013/96479951-e20ef900-1239-11eb-9b30-3f8d4c679972.png)
![image](https://user-images.githubusercontent.com/56630013/96479967-e4715300-1239-11eb-8e3f-4f67aefab200.png)

**Comment by nickdos** [comment]
Thanks @sylmorin-gbif - will take a look at this regression.
