### ISSUE TITLE
Taxa searches not working for some names (in APNI)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#275]
https://biocache.ala.org.au/occurrences/search?taxa=Diuris+oporina

is returning  a "text:" search result set but there is an APNI source for this name: https://bie.ala.org.au/species/http://id.biodiversity.org.au/name/apni/117448

Issue  appears to be the lack of an `acceptedIdentifier` in BIE WS call: https://bie.ala.org.au/ws/guid/batch?q=Diuris%20oporina

![image](https://user-images.githubusercontent.com/532845/44559989-c0687300-a790-11e8-9b0a-cbbcaec49d66.png)

**Comment by nickdos** [comment]
Added temp fix to "fail-over" to the `identifier` in these cases. Hopefully this will not cause any down-stream problems.

**Comment by ansell** [comment]
Testing for this looks good so far, based on running through the helpdesk issues opened for taxa search broadening on the beta sites and since we switched beta into production. 

I am updating and redeploying ala-hub (biocache-test), avh-hub (avh-test), ozcam-hub (ozcam-test) and asbp-hub (asbp-test) and will test more of the helpdesk issue species to see how many we can close off with this fix.

**Comment by nickdos** [comment]
Looks good to me, closing
