### ISSUE TITLE
display caption and image from image metadata with image

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-hubs#283]
caption is important for display of some herbarium images from APII e.g. https://biocache.ala.org.au/occurrences/fe9f99cb-e793-4ba0-9599-219f7fe9ce72 needs a caption to tell which sub image the record is for

**Comment by nickdos** [comment]
Looking at the JSON data from `biocache-service`, the field being used is `DESCRIPTION`, not the expected `caption`:

![image](https://user-images.githubusercontent.com/532845/55121545-0b939b80-514f-11e9-94c2-9fb1a5700fc0.png)

When we looked at this data @M-Nicholls we thought it was `caption`... is this a bug maybe?

**Comment by nickdos** [comment]
How does this look? Any suggestions for formatting or UI improvements?

![image](https://user-images.githubusercontent.com/532845/55121948-033c6000-5151-11e9-9844-eaea1422e63a.png)

**Comment by nielsklazenga** [comment]
Looks good.

As for `description` versus `caption`, `description` is Dublin Core and `caption` is Audubon Core. Audubon Core added `caption`, as there is a very slight difference. `description` should always be there, unless the image is purely ornamental, and is what should go in the `alt` attribute of an `img` tag. `caption` is, well, a caption and can go in a `figcaption` tag. While the purpose is slightly different, the value of `description` and `caption` is nine out of ten times the same. The `caption` tag was added to account for the one out of ten case where you might want the caption to be different from the `description`.

It would be ideal if it were possible to use `caption` if there is one and otherwise `description`. I wouldn't hesitate to do it the other way around, if I needed an `alt` attribute.

**Comment by nickdos** [comment]
Deployed, so closing.
