### ISSUE TITLE
messages.properties vs messages_en.properties

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/biocache-hubs#306]
I'm doing some sync work between crowdin and github and viceversa:
https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/305

I see that his repo has some `messages.properties` and `messages_en.properties` with minimal diferences. Other repositories only have `messages.properties`. Can be both merged? If not, which one should be uploaded to crowdin?

Currently my PR will upload `messages.properties` and delete `messages_en.properties` when downloading translations but I can reconfigure it depending on your answers. 

cc @ansell @djtfmartin and @nickdos that updated `messages_en.properties` in the past.

**Comment by nickdos** [comment]
I think IntelliJ is causing this, when using the `Refactor -> Internationalize` function.

**Comment by nickdos** [comment]
I've done a commit to remove all entries from `messages.properties` because we were seeing a strange bug on our server (but not locally) where entries in `messages.properties` were not being rendered.  

![image](https://user-images.githubusercontent.com/532845/69770547-87158300-11dd-11ea-86f2-10cdc499e16d.png)

So hoping this decides the dilemma.

**Comment by ansell** [comment]
@nickdos What is the status of this issue?

**Comment by nickdos** [comment]
`messages.properties` is now empty apart from a comment line, saying to use `messages_en.properties. Closing.
