### ISSUE TITLE
i18n labels for user assertions table display inconsistently in ala-hub

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#382]
Some i18n labels are not appearing correctly for some users in the User flagged issues table on records. Attached screenshots show views from two different users simultaneously - one shows the labels, the other does not.

I created the screenshot with the missing labels, and the next day refreshing the same record displayed them correctly. Subsequent refreshes showed the page with missing labels again. So it may be that one instance in the load balancer is not displaying the labels correctly, and refreshing the page occasionally is causing a change in which one the request is served by.

The example record below is: https://biocache.ala.org.au/occurrences/a40ccd76-8d69-4eb9-a0c5-ce503d8df8b4

<img width="1087" alt="assertions labels" src="https://user-images.githubusercontent.com/57081387/96051244-d2ed1b80-0ec6-11eb-8d42-d2cf4c6e75ba.png">
<img width="633" alt="assertions no labels" src="https://user-images.githubusercontent.com/57081387/96051250-d41e4880-0ec6-11eb-875c-568960d6f03d.png">

**Comment by nickdos** [comment]
This appears to be an issue where one of the 2 load-balanced servers, is showing the codes and other one is showing the correct text. I suspect this is due to ala-hub (in biocache-hubs code) is pulling in i18n codes from biocache-ws.ala.org.au/ws. I think that is failing for one of the nodes and might be due to throttling in Nginx.

**Comment by ansell** [comment]
To test the theory that it may be due to Nginx rate limiting, you would need to run browser developer tools when it is happening for you and see if the i18n property files are being successfully fetched by your browser.

**Comment by nickdos** [comment]
@ansell the i18n loading is happening on the server between ala-hub and biocache-service - see [code](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/develop/src/main/groovy/au/org/ala/biocache/hubs/BiocacheHubsGrailsPlugin.groovy#L102) but it seems to be set to a 6 hour timeout so unlikely to trigger rate limiting.

**Comment by ansell** [comment]
That path isn't being throttled currently for biocache-service.

**Comment by nickdos** [comment]
Looked at src and it does appear that the content is inserted via JS after all.

**Comment by nickdos** [comment]
Code review requested https://upsource.ala.org.au/biocache-hubs/review/BH-CR-54

**Comment by alexhuang091** [comment]
> Code review requested https://upsource.ala.org.au/biocache-hubs/review/BH-CR-54

comment added

**Comment by alexhuang091** [comment]
I haven't done enough test on this, but seems it's caused by how we load i18n.

I added a debug line to print the i18n text
```
var userAssertionStatus = jQuery.i18n.prop("user_assertions." + data.userAssertionStatus);
console.log('xhk205 user assertion status = ' + userAssertionStatus) // test line
$("#userAssertionStatus").text(userAssertionStatus);
```

remember the i18n settings is like this:
```
    jQuery.i18n.properties({
        name: 'messages',
        path: OCC_REC.contextPath + '/messages/i18n/',
        mode: 'map',
        async: true,
        cache: true,
        language: OCC_REC.locale // default is to use browser specified locale
        //callback: function(){} //alert( "facet.conservationStatus = " + jQuery.i18n.prop('facet.conservationStatus')); }
    });
```

with default `async:true` settings, the output is:
<img width="568" alt="async" src="https://user-images.githubusercontent.com/61677987/104679652-46aaf880-5742-11eb-962c-bdb392fdd22b.png">

if we change it to `async: false`
<img width="584" alt="sync" src="https://user-images.githubusercontent.com/61677987/104679683-5a565f00-5742-11eb-83cb-8ebd8695b400.png">

since we set i18n loading to be async, UI draw happens before i18n text returns, thus causing some text un-translated

**Comment by nickdos** [comment]
I added a comment to the code review - the fix I deployed above fixed the issue when I tested it with `develop` but maybe conflicts in merging have broken it again - please check the commit changes I have above to make sure they weren't accidently modified by the merge.

**Comment by alexhuang091** [comment]
`User Assertion Status` section is removed so it won't be an issue
