### ISSUE TITLE
Add link to `/admin` page to DQ filters admin UI

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#458]
Prod URL is https://data-quality-service.ala.org.au/

Add a link to this on [`/admin`](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/develop/grails-app/views/admin/index.gsp) page.

**Comment by alexhuang091** [comment]
Hi @nickdos actually the `Filters` is a link to `data-quality` page.

Maybe make it more clear? Use a link instead of a button? with text like 'Go to data-quality admin console/page' ?

<br/>
<br/>

![1](https://user-images.githubusercontent.com/61677987/129134015-fadb8b59-1d71-4fc9-9e18-3f981f390fbe.jpg)

**Comment by nickdos** [comment]
OK I missed it there (oops). 

Yeah I think it needs to be more obvious. 

Maybe remove the "filters" button and change the blue panel (remove the `alert alert-info` class) to be a simple link with the text:

[Data Quality filters admin interface](https://data-quality-service.ala.org.au/data-profiles)

**Comment by alexhuang091** [comment]
Hi @nickdos, how about his.

<img width="932" alt="截屏2021-08-12 下午3 47 09" src="https://user-images.githubusercontent.com/61677987/129144561-956d6e13-1f49-4839-9744-ee84baa0e9c0.png">

**Comment by alexhuang091** [comment]
Fixed padding.

<img width="1119" alt="截屏2021-08-12 下午4 04 03" src="https://user-images.githubusercontent.com/61677987/129146107-43e6974e-8fb0-466d-86f1-247f26148dbf.png">

**Comment by nickdos** [comment]
Looks good 👍
